### ISSUE TITLE
Passing SSO code to ESI to verify and get character information

### ISSUE THREAD

**Issue by IPFR33LY** [Adarnof/adarnauth-esi#1]
I have a working Angular 2 front-end that handles the redirect/callback of getting an SSO code.

I was trying to figure out how I can directly give your ESI App the Code+State recieved from the SSO Callback on the front-end side. I think I would try to use REST Framework to make a POST request with the Code/State in the body of that request but I'm not sure if I can do that with this app?

How would you integrate REST API into your app to have your App process the backend stuff?

**Comment by Adarnof** [comment]
If you've got a front-end handling redirects then it's not necessary to pass state to the app as it's not used in the token exchange. Your front-end should be validating the state.

The app was not built with APIs in mind, so there's no straight-forward way to pass the code along. The [manager method](https://github.com/Adarnof/adarnauth-esi/blob/v1.2.2/esi/managers.py#L75) expects the code as a GET parameter, not in the body, as that's how it's returned from the OAuth exchange. The quick-and-dirty way of passing it along is to write a simple API view in your django project which accepts GET requests with a code, then passes the request along to the manager:

    @require_GET
    def create_token(request):
        token = Token.objects.create_from_request(request)

The *better* way would be for me to pull the code exchange logic out of the `create_from_request` and into its own `create_from_code` method. This way your view could accept POST and pull it from the body, then pass this code to the manager. If this is sufficient for your project I can get it done quick.

**Comment by IPFR33LY** [comment]
Yeah. That would be splendid! Your App is fantastic and maybe making it
more API friendly would be make it even better.

**Comment by Adarnof** [comment]
Alright I've done that in 1757f17 - I'll bump to v1.3 as well.

**Comment by Adarnof** [comment]
I finally got around to publishing the release - sorta forgot to push that button. Case closed!
