### ISSUE TITLE
ReadMe typos

### ISSUE THREAD

**Issue by rossos** [Adarnof/adarnauth-esi#2]
I'm new to Django and Python, so these might be issues of ignorance on my part, but do two of the instructions given by your ReadMe contain typos?

The readme QuickStart guide says to include the esi urlconf with this
`url(r'^sso/', include('esi.urls'), namespace='esi'),`
but this gives me the error

> url() got an unexpected keyword argument 'namespace'

which is resolved by instead setting the urlconf using
`url(r'^sso/', include('esi.urls', namespace='esi')),`
with the shifted parenthesis.

Later, under "Getting a Client", the readme says to import
`from esi.client`
but this gives the ImportError
> No module named 'esi.client'

which is resolved by instead importing
`from esi.clients`

**Comment by Adarnof** [comment]
Sorry I hadn't gotten around to fixing it. Yup you're right, and I've updated the readme. Thanks!
